In [6]:
import numpy as np
a=np.array([10,20,30,40,50])
#copy
d=a.copy()
d[1]=77

print("original after copy change: ",a)
print("copy array: ",d)


#view
b=a.view()
b[0]=99

print("original after view change: ",a)
print("view only: ",b)


#copy
c=a.copy()
c[1]=77

print("original after copy change: ",a)
print("copy array: ",c)

original after copy change:  [10 20 30 40 50]
copy array:  [10 77 30 40 50]
original after view change:  [99 20 30 40 50]
view only:  [99 20 30 40 50]
original after copy change:  [99 20 30 40 50]
copy array:  [99 77 30 40 50]


In [1]:
#diff btw copy and view in an array
#copy=new array,any changes in new array doesn't affect the orginal array
#view=just the view of original array(existing array) #any changes in original array affect the view
#ex of copy
import numpy as np
beauty=np.array([1,2,3,4,5])
x=beauty.copy()
beauty[0]=45
print(beauty)
print(x)


[45  2  3  4  5]
[1 2 3 4 5]


In [ ]:
#view
import numpy as np
beauty=np.array([1,2,3,4,5])
x=beauty.view()
beauty[0]=45
print(beauty)
print(x)

[45  2  3  4  5]
[45  2  3  4  5]


In [3]:
#check if array owns its data
#print the value of the base attribute to check f an array owns its data or not
beauty=np.array([1,2,3,4,5])
x=beauty.copy()
y=beauty.view()
print(x.base)
print(y.base)


None
[1 2 3 4 5]
