In [2]:
#in two d
import numpy as np
beauty=np.array([[1,2,3,4,5],[1,2,3,7,8]])
for x in beauty:
    print(x)


[1 2 3 4 5]
[1 2 3 7 8]


In [ ]:
#iterating  in 1d
import numpy as np
beauty=np.array([1,2,3,4,5])
for x in beauty:
    print(x)

In [ ]:
#in 3d
beauty=np.array([[[1,2,3],[3,6,7]],[[5,6,7],[8,7,9]]])
for x in beauty:
    print(x)


In [ ]:
#iterate in each sacle element of the 2d
beauty=np.array([[[1,2,3],[3,6,7]],[[5,6,7],[8,7,9]]])
for x in beauty:
    for y in x:
        for z in y:
            print(z)

In [8]:
#another way: by using nditer()
#itis a helping function for advanced iteration
#iterate through 3d array
beauty=np.array([[[1,2,3],[3,6,7]],[[5,6,7],[8,7,9]]])
for x in np.nditer(beauty):
    print(x)



#.ndenumerator()-getindex+value
for x in np.ndenumerate(beauty):
    print(x)


#modify while iterating
#op_flag['readwrite']
for x in np.nditer(beauty,op_flags=['readwrite']):
    x[...]=x*2
print(beauty)






1
2
3
3
6
7
5
6
7
8
7
9
((0, 0, 0), np.int64(1))
((0, 0, 1), np.int64(2))
((0, 0, 2), np.int64(3))
((0, 1, 0), np.int64(3))
((0, 1, 1), np.int64(6))
((0, 1, 2), np.int64(7))
((1, 0, 0), np.int64(5))
((1, 0, 1), np.int64(6))
((1, 0, 2), np.int64(7))
((1, 1, 0), np.int64(8))
((1, 1, 1), np.int64(7))
((1, 1, 2), np.int64(9))
[[[ 2  4  6]
  [ 6 12 14]]

 [[10 12 14]
  [16 14 18]]]
