In [7]:
#joining the array using stack function
import numpy as np
a=np.array([10,20,30,40,50])
b=np.array([10,20,30,40,50])
c=np.stack((a,b))
print(c)

[[10 20 30 40 50]
 [10 20 30 40 50]]


In [ ]:
#joining the array 
import numpy as np
a=np.array([10,20,30,40,50])
b=np.array([10,20,30,40,50])
c=np.concatenate((a,b))
print(c)

beauty=np.array([[1,2,3],[6,7,8]])
beauty1=np.array([[1,2,3],[6,7,8]])
d=np.concatenate((beauty,beauty1))
print(d)




In [9]:
#joining the array using stack function
#differents types of stack
import numpy as np
a=np.array([10,20,30,40,50])
b=np.array([10,20,30,40,50])
c=np.hstack((a,b))
d=np.vstack((a,b))
print(c)
print(d)

e=np.dstack((a,b))
print(e)

[10 20 30 40 50 10 20 30 40 50]
[[10 20 30 40 50]
 [10 20 30 40 50]]
[[[10 10]
  [20 20]
  [30 30]
  [40 40]
  [50 50]]]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.dstack((a, b))
print(result)
