In [6]:
#create a numpy ndarray object
import numpy as np
shared=np.array([1,2,3,4,5])
print(shared)
print(type(shared))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#whatever object you will pass in it,automatically get converted in array
import numpy as np
shared=np.array((1,2,3,4,5))
print(shared)
print(type(shared))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [14]:
#dimension of array-nested array (that have array as an element(array under array))
#0D=create
import numpy as np
shared=np.array(50)
print(shared)
#1D=create
shared=np.array([1,2,3])
print(shared)
#2D-create
shared=np.array([[1,2,3,4],[1,2,3,4]])
print(shared)
#3D-create- create with two d array...
shared=np.array([[[1,2,3],[1,2,3]],[[1,3,4],[6,8,9]]])
print(shared)


50
[1 2 3]
[[1 2 3 4]
 [1 2 3 4]]
[[[1 2 3]
  [1 2 3]]

 [[1 3 4]
  [6 8 9]]]


In [2]:
import numpy

shared=numpy.array([1,2,3,4,5])
print(shared)

[1 2 3 4 5]


In [ ]:
import numpy as np
shared=np.array([1,3,4,5])
print(shared)
print(np.__version__)


[1 3 4 5]
2.3.4


In [ ]:
#checking the number of dimension?
#ndim
import numpy as np
a=np.array(34)
b=np.array([1,2,3,4])
c=np.array([[1,2,3],[1,2,4]])
d=np.array([[[1,2,3],[4,5,6]],[[5,6,7],[6,7,8]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#higher dimensional array-you can define the number of dimension by using ndimn
import numpy as np
shared=np.array([1,2,3,4,5],ndmin=5)
print(shared)

#ndmin=it ensure the numpy array has at least given number of dimension
#ndmin=minimum number of dimension

[[[[[1 2 3 4 5]]]]]
