In [ ]:
#numpy.random lets you generate random numbers, arrays, and even choices from data.
import numpy as np

x = np.random.randint(100)   # integer from 0 to 99
print(x)
x1 = np.random.rand() #btw 0 to 1
print(x1)

8
0.37425056052764527


In [ ]:
#Generate random array
arr = np.random.randint(100, size=5)
print(arr)
arr1 = np.random.randint(100, size=(3, 4))
print(arr1)

[39 54 22 72 91]
[[85 63 18  2]
 [18 86 24 10]
 [77 63 12  9]]


In [ ]:
#random floats
arr = np.random.rand(3, 2)
print(arr) #raange is always 0 to 1


[[0.400822   0.2894109 ]
 [0.58949428 0.17405446]
 [0.76463859 0.72239761]]


In [7]:
#Random choice from a list
arr = np.array([10, 20, 30, 40, 50])
choice = np.random.choice(arr)
print(choice)
#also pick multiple random element
choices = np.random.choice(arr, size=3)
print(choices)



40
[40 20 50]


In [ ]:
#Shuffle (reorder array randomly)
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)
#shuffle() changes the original array

[1 5 3 4 2]


In [ ]:
#Permutation (random reorder copy)
arr = np.array([1, 2, 3, 4, 5])
new_arr = np.random.permutation(arr)
print(new_arr)
#Doesn’t affect the original array.

[5 3 4 2 1]


In [10]:
# Random from Normal Distribution
arr = np.random.normal(0, 1, 5)  # mean=0, std=1, size=5
print(arr)


[-0.26484749 -0.60994706  2.88728391 -0.05819081 -1.34404655]


In [11]:
# Random Seed (to repeat results)
#same random output every time
np.random.seed(42)
print(np.random.randint(100, size=5))


[51 92 14 71 60]
