In [3]:
#searching in array
#where
import numpy as np
a=np.array([1,2,3,4,5,4,4])
b=np.where(a==4)
print(b)


(array([3, 5, 6]),)


In [5]:
#where index is even
a=np.array([1,2,3,4,5,4,4,0])
b=np.where(a%2==0)
print(b)


(array([1, 3, 5, 6, 7]),)


In [6]:
#where index is odd
a=np.array([1,2,3,4,5,4,4,0])
b=np.where(a%2==1)
print(b)


(array([0, 2, 4]),)


In [ ]:
#search sorted method searchsorted() by default it is left to right
#where index is even
a=np.array([1,2,3,4,5,4,4,0])
b=np.searchsorted(a,4)
print(b)


3


In [ ]:
#search from right to left
a=np.array([1,2,3,4,5,4,4,0])
b=np.searchsorted(a,4,side='right')
print(b)


3


In [12]:
#search from right to left
a=np.array([1,2,3,4,5,4,4,0])
b=np.searchsorted(a,[2,4,6])
print(b)


[1 3 8]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
x = np.where(arr == 30)
print(x)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
x = np.where(arr % 2 == 0)
print(x)


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6])
even_values = arr[np.where(arr % 2 == 0)]
print(even_values)


[2 4 6]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
x = np.searchsorted(arr, 35)
print(x)


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
x = np.searchsorted(arr, [25, 45])
print(x)


In [14]:
arr = np.array([10, 20, 5, 40, 15])
print("Max index:", np.argmax(arr))
print("Min index:", np.argmin(arr))


Max index: 3
Min index: 2


In [15]:
arr = np.array([0, 1, 0, 2, 3, 0])
x = np.nonzero(arr)
print(x)


(array([1, 3, 4]),)
