In [3]:
#numpy array shape
#print the shape of 2 d array 
import numpy as np
beauty=np.array([[12,45,67],[56,43,21]])
print(beauty.shape)
beauty1=np.array([1,2,3,4],ndmin=5)
print(beauty1)
print(beauty1.shape)

#two dimension 
#three element



(2, 3)
[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [4]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a.shape)


(5,)


In [10]:
#we can reshape the array using .reshape()
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaped=a.reshape(4,3)
print(reshaped)
print(reshaped.shape)
#the total number of element must stay the same after reshaping


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [15]:
#reshape from 1d to 3d
import numpy as np
beauty=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
beauty1=beauty.reshape(2,3,2)
print(beauty1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [17]:
#can we reshape in any shape
#equal in both shape
#try to convert 1 d array with 8 elemnt to 2d array with 3 elements each dimension
import numpy as np
beauty=np.array([1,2,3,4,5,6,7,8,9])
beauty1=beauty.reshape(3,3)
print(beauty1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#converting 1d array of 8 element to 3d
import numpy as np
beauty=np.array([1,2,3,4,5,6,7,8])
beauty1=beauty.reshape(2,2,-1) #unknown dimesnion 
print(beauty1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
#flattering=converting multidimensional array into one d
#use reshape(-1)
import numpy as np
beauty=np.array([[1,2,3],[6,7,8]])
beauty1=beauty.reshape(-1)
print(beauty1)

[1 2 3 6 7 8]
