In [ ]:
#numpy array slicing
# [start:end]or[start:end:step]
#[0:end]
import numpy as np
beauty=np.array([1,2,3,4,5,6,7])
print(beauty[1:5])
print(beauty[:4])
print(beauty[4:])
print(beauty[2:5:2])
print(beauty[3])

[2 3 4 5]
[1 2 3 4]
[5 6 7]
[3 5]
4


In [ ]:
#negative indexing=use minus operator to refer to an index from the end
#slice from the index 3 to the end
beauty=np.array([1,2,3,4,5,6,7])
print(beauty[-3:-1])

[5 6]


In [ ]:
#step=step in slicing
beauty=np.array([1,2,3,4,5,6,7,8,9,10])
print(beauty[::2])
print(beauty[1::2])

[1 3 5 7 9]
[ 2  4  6  8 10]


In [ ]:
#slicing in two d array
#from the 2nd element ,slice element from the index 1 to index 4
beauty=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(beauty[0,1:4]) #first row
print(beauty[1,2:4])#2nd row

print(beauty[0:2,2:4])



[2 3 4]
[8 9]
[[3 4]
 [8 9]]
