In [ ]:
#puting elementin order sequence
#sort()
#but it doesn't the changeanything in original array
import numpy as np
arr = np.array([0, 1, 0, 2, 3, 0])
print(np.sort(arr))
print(arr)


[0 0 0 1 2 3]
[0 1 0 2 3 0]


In [ ]:
beauty=np.array([3,2,4,5])
print(np.sort(beauty)) #ascending order by default


[2 3 4 5]


In [3]:
#sort in descending order
beauty=np.array([3,2,4,5])
print(np.sort(beauty)[::-1])

[5 4 3 2]


In [4]:
#sort 2 d array
arr = np.array([[3, 2, 1], [6, 5, 4]])
print(np.sort(arr))

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[3, 2, 1], [6, 5, 4]])
print(np.sort(arr)) #default axis is -1(row)

[[1 2 3]
 [4 5 6]]


In [6]:
#sort by col
arr = np.array([[3, 2, 1], [6, 5, 4]])
print(np.sort(arr, axis=0))


[[3 2 1]
 [6 5 4]]


In [9]:
#get the index of sorted array as output
arr = np.array([[3, 2, 1], [6, 5, 4]])
print(np.argsort(arr, axis=0))
arr = np.array([40, 10, 20, 30])
indexes = np.argsort(arr)
print(indexes)



[[0 0 0]
 [1 1 1]]
[1 2 3 0]


In [10]:
names = np.array(["D", "A", "C", "B"])
scores = np.array([40, 10, 20, 30])

sorted_names = names[np.argsort(scores)]
print(sorted_names)


['A' 'C' 'B' 'D']


In [11]:
arr = np.array(['banana', 'apple', 'cherry'])
print(np.sort(arr))


['apple' 'banana' 'cherry']
